---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  labels:
    name: nextcloud-pv
  namespace: nextcloud

spec:
  # If you leave storageClassName blank, it will be picked
  # up by k3s by default and use `local-path`, which won't mount
  # correctly
  storageClassName: nextcloud

  accessModes:
    - ReadWriteOnce

  capacity:
    storage: 5Gi

  hostPath:
    path: "/var/lib/k3d-data/mycluster/nextcloud"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-claim
  namespace: nextcloud

spec:
  storageClassName: nextcloud
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
